### ISSUE TITLE
Custom frame size and AUTO scrolling panels

### ISSUE THREAD

**Issue by anbjoernskov** [cadin/panels#16] opened 2023-11-02 07:22 UTC
Hi!
I have a problem with using the custom functions with the auto scrolling feature.
If I set the frame to another width (like 800 pixels) there is no scrolling with the crank.
I have managed to 'hack' that by changing the offset in the update function.
But the advance function doesn't work, unless it is the last panel in a sequence. Looks like it could come from the fact that the scrollPos is not updated?

It would be really nice if this could work 🙏

Thank you for a really nice framework - it is really great to work with!

**Comment by cadin** [comment] 2023-11-02 15:12
I'm seeing multiple issues when I test this:

1. Wide frames aren't scrollable in AUTO scrolling mode.   
This is the intended behavior. You should be able to auto scroll from the start to the end of the frame using the advance control. I can see why you might still want to scroll with the crank though. I'll give it some thought.

2. (Bug) Advance control doesn't work on wide frames.  
Pressing the advance control skips me to the end of the panel, but won't advance to the next one.  
Additionally, if I skip back to the start of the wide panel, the advance control won't jump to the end anymore.

3. (Bug) Using an advance function on wide frame breaks auto advancing.  
Strangely, this seems to break all auto-advancing in the sequence (not just on the wide panel).

**Comment by cadin** [comment] 2023-11-03 21:16
I fixed the bugs here (problems 2 & 3 above).
Try with the latest version of Panels (1.6.2) and let me know if you still have problems.

For the cranking thing, how are you wanting that to work? The user auto-scrolls to the start of the wide panel, then uses the crank to scroll to the end of the panel, then uses the advance control to auto-scroll to the next? Is that right?

In that case, would you want to disable having the advance control skip the user to the end of the wide panel without cranking?

I think this might be too niche to officially support, but I'll keep thinking about it.  
A couple workarounds that might work for you using the existing system:

1. Break the wide panel out into a separate sequence.  
This way you can have the wide panel set to manual scrolling with the sequence before and after set to auto. With that setup you'd get basically the behavior I described above. You can even hide the button graphics at the end of the sequences to make the transition seem less abrupt ([showAdvanceControl = false](https://cadin.github.io/panels/docs/comic-data/sequences.html#showadvancecontrol)).

2. Use custom functions to scroll the wide content _within_ a normal size panel.  
If you're comfortable with custom functions, you could use a normal sized panel, but listen for the crank and adjust the offset to have the content scroll within the small panel. You can then check to see if the user has scrolled to the end before letting them advance (with an `advanceFunction`).

Let me know what you think.

**Comment by anbjoernskov** [comment] 2023-11-04 14:39
The reason I am using an auto scrolling is to have the custom functions. So I have a wide panel, which the user has to scroll through, and ind the end there is something they will interact with (using the update function) and then the advance function will check when the user can move on. That's why I need the crank to scroll, as they arrows are used for the interaction, as well as the A and B button. 
Right now I can scroll the image by changing the offset.x, and maybe that's fine. I will check how it works with your update!
Thanks for the quick fix! Really appreciate it

**Comment by anbjoernskov** [comment] 2023-11-04 16:43
Your bugfixes works, but I have the problem that I haven't updated the scrollOffset variable (because it is hidden - for good reason), so when it transitions to the next panel it looks a bit weird, because the transition starts at the start of the wide panel. 
I tried scrolling the wide image in a normal size frame, and that looks indeed to be a solution.
I also understand that this might be to niche an idea, so maybe I will figure out some custom thing.

**Comment by cadin** [comment] 2023-11-18 19:56
Hi, just following up on this finally:

I couldn't come up with a good way to enable crank scrolling in auto-advance panels without breaking a bunch of other stuff. Since this is a pretty niche use case (I think), I'm going to close this for now. Hopefully one of the workarounds is acceptable for your project.

If there are other smaller changes that would make this work better for you let me know and I'll take another look.

**Closed by cadin** 2023-11-18 19:56 UTC
Labels: enhancement

**Comment by anbjoernskov** [comment] 2023-11-20 09:32
Thanks for looking into it!

I have a workaround so that I am able to scroll and interact at the same time, so that is fine :)

For future reference here is how I have done it:

```
function GameLogic.update(panel, offset, gameStates, gameConfigurations)
    local crankChange = playdate.getCrankChange()
    gameStates.scrollOffset = gameStates.scrollOffset + crankChange

    -- constrain the scroll offset to the min/max positions
    gameStates.scrollOffset = math.min(gameStates.scrollOffset, gameConfigurations.maxPosition)
    gameStates.scrollOffset = math.max(gameStates.scrollOffset, gameConfigurations.minPosition)

    if panel.direction == Panels.ScrollDirection.TOP_DOWN then
        offset.y = offset.y - gameStates.scrollOffset
    else
        offset.x = offset.x - gameStates.scrollOffset
    end
.....
```

and then used that as the update function for that panel. The only problem is then, that this has to be the last panel in the sequence, otherwise weird things happen :)
